<%
  mongohq_url = URI.parse(ENV['MONGOHQ_URL']) rescue nil
  mongoid_host = mongohq_url.andand.host || ENV['MONGOID_HOST']
  mongoid_port = mongohq_url.andand.port || ENV['MONGOID_PORT']
  mongoid_username = mongohq_url.andand.user || ENV['MONGOID_USERNAME']
  mongoid_password = mongohq_url.andand.password || ENV['MONGOID_PASSWORD']
  mongoid_database = mongohq_url.andand.path.andand.gsub(/^\//, '') || ENV['MONGOID_DATABASE']
%>
defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: beautifulwebsites_development

test:
  <<: *defaults
  database: beautifulwebsites_test

# set these environment variables on your prod server
production:
  host: <%= mongoid_host %>
  port: <%= mongoid_port %>
  username: <%= mongoid_username %>
  password: <%= mongoid_password %>
  database: <%= mongoid_database %>